Repository friendsoftwig/twigcs, pull requests merged in 2022-04, with the labels that each got.

#197 Fix: Remove Travis CI configuration
  .travis.yml
Labels: bug

#198 Enhancement: Add `.gitattributes`
  .gitattributes
Labels: enhancement

#199 Fix: Do not prefer to install from source
  .github/workflows/ci-tests.yaml
Labels: bug

#200 Fix: Do not bother installing `phpunit` with `shivammathur/setup-php`
  .github/workflows/ci-tests.yaml
Labels: bug

#201 Fix: Rename workflow
  .github/workflows/integrate.yaml
Labels: bug

#202 Fix: Wrap arrays
  .github/workflows/integrate.yaml
Labels: bug

#203 Fix: Consistently quote strings in YAML files
  .github/workflows/integrate.yaml
Labels: bug

#206 Fix: Order
  .github/workflows/integrate.yaml
Labels: bug

#207 Enhancement: Add badge
  README.md
Labels: enhancement

#211 Enhancement: Add issue and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#210 Fix: Rename steps
  .github/workflows/integrate.yaml
Labels: bug

#212 Fix: Run workflow on push and pull_request events
  .github/workflows/integrate.yaml
Labels: bug

#213 Fix: Do not bother running workflow on macos-latest
  .github/workflows/integrate.yaml
Labels: bug

#215 Fix: Clean up `.gitignore`
  .gitignore
Labels: bug

#178 Apply php-cs-fixer and add a GA job to check it
  .gitattributes
  .github/workflows/integrate.yaml
  .gitignore
  .phive/phars.xml
  .phive/php-cs-fixer
  src/Reporter/JsonReporter.php
  src/Rule/ForbiddenFunctions.php
  src/Rule/LowerCaseVariable.php
  src/TwigPort/SyntaxError.php
  src/TwigPort/TokenStream.php
  src/Validator/Violation.php
  tests/Reporter/JsonReporterTest.php
Labels: enhancement

#216 Enhancement: Update `friendsofphp/php-cs-fixer`
  .gitattributes
  .gitignore
  .phive/phars.xml
  .phive/php-cs-fixer
  .php-cs-fixer.dist.php
  src/Console/Application.php
  src/Console/LintCommand.php
  src/Lexer.php
  src/RegEngine/RulesetBuilder.php
  src/RegEngine/RulesetConfigurator.php
  src/RegEngine/Sanitizer/StringSanitizer.php
  src/Reporter/JsonReporter.php
  src/Scope/ScopeBuilder.php
  src/TwigPort/Token.php
  src/TwigPort/TwigLexer.php
  src/Validator/Violation.php
  tests/CorpusTest.php
  tests/Reporter/CheckstyleReporterTest.php
  tests/Reporter/JsonReporterTest.php
  tests/Rule/ForbiddenFunctionsTest.php
Labels: enhancement

#217 Fix: Use long option
  .github/workflows/integrate.yaml
Labels: bug

#218 Enhancement: Use `--ansi` option
  .github/workflows/integrate.yaml
Labels: enhancement

#219 Enhancement: Allow dependabot to update GitHub Actions
  .github/dependabot.yaml
Labels: enhancement

#221 Fix: Disable coverage
  .github/workflows/integrate.yaml
Labels: bug

#222 Enhancement: Add `.editorconfig`
  .editorconfig
  .gitattributes
Labels: enhancement

#224 Enhancement: Keep packages sorted in `composer.json`
  composer.json
Labels: enhancement

#223 Enhancement: Run dependency analysis with `maglnet/composer-require-checker`
  .gitattributes
  .github/workflows/integrate.yaml
  .phive/composer-require-checker
  .phive/phars.xml
  composer-require-checker.json
  composer.json
Labels: enhancement, dependency

#225 Fix: Reference `phpunit.xsd` as installed with `composer`
  phpunit.xml.dist
Labels: bug

#226 Fix: Remove comment
  phpunit.xml.dist
Labels: bug

#227 Fix: Indentation
  phpunit.xml.dist
Labels: bug

#228 Fix: Order
  phpunit.xml.dist
Labels: bug

#229 Fix: Require `phpunit/phpunit:^9.5.20`
  composer.json
Labels: bug, dependency

#230 Enhancement: Collect and report code coverage
  .github/workflows/integrate.yaml
  .gitignore
  README.md
  phpunit.xml.dist
Labels: enhancement

#231 Fix: Order
  .php-cs-fixer.dist.php
Labels: bug

#233 Fix: Add `CONTRIBUTING.md`
  .github/CONTRIBUTING.md
  README.md
Labels: bug

#234 Enhancement: Add `Makefile`
  .editorconfig
  .gitattributes
  .github/CONTRIBUTING.md
  Makefile
Labels: enhancement

#235 Fix: Require `humbug/box`
  .phive/box
  .phive/phars.xml
  bin/release
Labels: bug, dependency

#236 Enhancement: Compile Phar
  .github/CONTRIBUTING.md
  .github/workflows/integrate.yaml
  Makefile
Labels: enhancement

#237 Enhancement: Validate `box.json.dist` before compiling Phar
  .github/workflows/integrate.yaml
  Makefile
  box.json.dist
Labels: enhancement

#238 Enhancement: Run `phpunit/phpunit` in `verbose` mode
  phpunit.xml.dist
Labels: enhancement

#239 Fix: Do not install development dependencies when compiling Phar
  .github/workflows/integrate.yaml
  Makefile
Labels: bug
